<?php

namespace Feature\Teams;

use Heart\Team\Infrastructure\Models\Invite;
use Heart\Team\Infrastructure\Models\Team;
use Heart\User\Infrastructure\Models\User;
use Illuminate\Foundation\Http\FormRequest;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class HandleInviteTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->team = Team::factory()->create(['slug' => 'he4rtless']);
        $inviter = User::factory()->create();
        $user = User::factory()->create();

        $this->invite = Invite::factory()->create([
            'team_id' => $this->team->id,
            'invited_by' => $inviter->id,
            'member_id' => $user->id,
        ]);

        // TODO as paradas de auth
    }

    public function test_user_can_accept_invite(): void // PRECISA DE USER
    {
        $this->postJson(route('teams.handle.invite', ['invitation' => $this->invite->id]), [
            'answer' => 'accept',
        ])
            ->assertCreated()
            ->assertJsonStructure([
                'id',
                'team_id',
                'member_id',
                'role_id',
            ]);
    }

    public function test_user_can_decline_invite(): void
    {
        $this->postJson(route('teams.handle.invite', ['invitation' => $this->invite->id]), [
            'answer' => 'decline',
        ])
            ->assertOk()
            ->assertContent('"The invite has been declined"');
    }
}
