<?php

namespace Tests\Feature\Gamefication;

use App\Models\User\User;
use Illuminate\Support\Facades\Artisan;
use Laravel\Lumen\Testing\DatabaseMigrations;
use Mockery as m;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;

class ExperienceLevelingTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed');
        config(['he4rt.season.id' => 1]);
        config(['gambling.xp.message' => 5]);
    }

    public function test_user_can_level_up()
    {
        $user = User::factory()->create([
            'level' => 1,
            'current_exp' => 9
        ]);

        $this->post(route('users.messages.store', ['discordId' => $user->discord_id]), [
            'message' => 'fodase essa porra'
        ], $this->getHeaders())->seeStatusCode(Response::HTTP_NO_CONTENT);



        $this->seeInDatabase('users', [
            'id' => $user->getKey(),
            'level' => 2
        ]);

        $this->notSeeInDatabase('users', [
            'id' => $user->getKey(),
            'current_exp' => 9
        ]);
    }

    public function test_user_can_gain_experience()
    {
        $user = User::factory()->create(['current_exp' => 0]);
        $user->messages()->create([
            'message' => 'fodase'
        ]);

        $this->notSeeInDatabase('users', [
            'id' => $user->getKey(),
            'current_exp' => 0
        ]);
    }
}
