<?php

namespace Tests\Feature\Message;

use Heart\Character\Infrastructure\Models\Character;
use Heart\Meeting\Infrastructure\Models\Meeting;
use Heart\Provider\Infrastructure\Models\Provider;
use Heart\User\Infrastructure\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\Cache;
use Mockery as m;
use Tests\TestCase;

class NewMessageTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        m::close();
        Cache::tags(['meetings'])->flush();
    }

    public function testCanCreateAMessage(): void
    {
        $user = User::factory()
            ->has(Character::factory(['experience' => 1]), 'character')
            ->has(Provider::factory(), 'providers')
            ->create();
        $provider = $user->providers[0];
        $payload = [
            'provider' => $provider->provider,
            'provider_id' => $provider->provider_id,
            'provider_message_id' => '12312312',
            'channel_id' => '312321',
            'content' => '321312',
            'sent_at' => now()->toDateTimeString()
        ];

        $this
            ->postJson(route('messages.create', ['provider' => $provider->provider]), $payload)
            ->assertNoContent();

        $this->assertDatabaseMissing('characters', [
            'user_id' => $user->getKey(),
            'experience' => 1
        ]);
    }

    public function testCanCreateAMessageAndReceiveAMeetingCheck()
    {
        $user = User::factory()
            ->has(Character::factory(['experience' => 1]), 'character')
            ->has(Provider::factory(), 'providers')
            ->create();

        $meeting = Meeting::factory()
            ->unfinished()
            ->create();

        Cache::tags(['meetings'])->put('current-meeting', $meeting->id);

        $provider = $user->providers[0];
        $payload = [
            'provider' => $provider->provider,
            'provider_id' => $provider->provider_id,
            'provider_message_id' => '12312312',
            'channel_id' => '312321',
            'content' => '321312',
            'sent_at' => now()->toDateTimeString()
        ];

        $this
            ->postJson(route('messages.create', ['provider' => $provider->provider]), $payload)
            ->assertNoContent();

        $this->assertDatabaseMissing('characters', [
            'user_id' => $user->getKey(),
            'experience' => 1
        ]);

        $this->assertDatabaseHas('meeting_participants', [
            'meeting_id' => $meeting->id,
            'user_id' => $user->id
        ]);
        $userAttendedCacheKey = sprintf('meeting-%s-attended', $user->id);
        $this->assertTrue(Cache::tags(['meetings'])->has($userAttendedCacheKey));
        Cache::tags(['meetings'])->flush();

        $this->assertFalse(Cache::tags(['meetings'])->has($userAttendedCacheKey));
    }
}
